### ISSUE TITLE
flask.g가 life of request동안 data를 저장한다는데 무슨 소리인가요?

### ISSUE THREAD

**Issue by chiquitabanana22** [chiquitabanana22/Banana-homework#2]

**Comment by yurica** [comment]
Scope와 관련된 개념을 찾아보시면 됩니다.
Request, Session, Application Scope가 있는데 찾아보면서 개념적인 구분 해보면 좋겠네요. 각각이 무슨 말이고 보통 어떤 정보가 저장되는지 예시 정도만. 간단히만 알아보시고 실무에서 직접 판단하면서 배우시게 될거에요.

**Comment by chiquitabanana22** [comment]
request scope: http 요청이 지속되는 범위, 요청이 끝나면 필요없어지는 정보 등 저장(로그인 시도 시 비밀번호 틀리면 처음 입력했던 비밀번호 날아가는 그런 것 같음)
session scope: 세션이 지속되는 범위, 세션은 브라우저가 꺼지기 전까지이고, 은행 사이트처럼 30분 후 로그아웃 등으로 설정 가능한듯
application scope: 서버가 꺼지기 전까지 지속되는 범위
